#set_default(:default_email_user, "alert.factor3@gmail.com")
#set_default(:monit_alert_email, "eduardodeoh@gmail.com")
#set_default(:monit_alert_email_server, "smtp.gmail.com")
#set_default(:monit_alert_email_server_port, 587)
#set_default(:monit_alert_email_username) {"#{default_email_user}"}
#set_default(:monit_alert_email_username_password) {"#{email_password}"}
#set_default(:logwatch_email, "eduardodeoh@gmail.com")
#set_default(:logwatch_email_server, "smtp.gmail.com")
#set_default(:logwatch_email_server_port, 587)
#set_default(:logwatch_email_username) {"#{default_email_user}"}
#set_default(:logwatch_email_username_password) {"#{email_password}"}